title: Rohan Alibutud
email: rohan.alibutud@temple.edu
office: SERC-610F, Temple University, Philadelphia PA
description: >- # Personal and professional webpage
  Under construction
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# If you want to use a theme supported by GitHub Pages:
theme: minima # Example theme
